### ISSUE TITLE
non semver versioning

### ISSUE THREAD

**Issue by craigh** [zikula-modules/Files#21]
@jguille2 
Zikula follows the [semver](http://semver.org) standard when versioning. Using a non standard like `1.0.2.1` will likely result in problems down the road. I would strongly suggest using standard versioning and so in this case `1.0.3`.

**Comment by jguille2** [comment]
Hi @craigh!
I'm sorry.
1.0.2.1 is not a new version. Only a tag (fixing bugs) to synch updates with other repos.
If this is a problem, I'll delete this tag.

**Comment by jguille2** [comment]
@craigh 
Waiting your answer: deleting tag or I close directly this issue?

**Comment by craigh** [comment]
well, it is listed here https://github.com/zikula-modules/Files/releases as a release. So it *is* a new version. I just think it is confusing. I suggest deleting and changing to 1.0.3

**Comment by jguille2** [comment]
Ok
New version (1.0.3) made.

Thanks
