### ISSUE TITLE
TinyMCE icon not showing up

### ISSUE THREAD

**Issue by robbrandt** [zikula-modules/Files#22]
In Scribite 5.x, the Files icon in TinyMCE isn't showing up.
This part:
editor.addButton('files', {
		tooltip: 'Files plugin',
		icon: 'paperclip',
		onclick: OpenFilesDialog
	});
needs to be changed to:

editor.addButton('files', {
		tooltip: 'Files plugin',
		icon: 'true',
                image: tinyMCE.baseURL + '/plugins/files/imgs/files.gif',
		onclick: OpenFilesDialog
	});

And then it works.

**Comment by shefik** [comment]
@robbrandt Can you try it again, using this line instead:

```image: Zikula.Config.baseURL+'/plugins/files/imgs/files.gif',```

Also, in which file are you modifying this code?

**Comment by shefik** [comment]
Also, shouldn't this ticket be posted in this project instead?

https://github.com/zikula-modules/Scribite

**Comment by jguille2** [comment]
Hi @robbrandt,

Have you copied all the files? In Scribite5, TinyMCE plugin is not using files.gif. It use a font generated from icomoon (I generated new font files adding a paperclip).

Make sure to follow [install instructions](https://github.com/zikula-modules/Files/blob/master/Resources/tinyMCEplugin/README.md).
Maybe it is useful this [fork](https://github.com/intraweb-modules13/Scribite/releases). It's Scribite 5.0.0 with Files plugins included.

@shefik. Acording [this ticket](https://github.com/zikula-modules/Scribite/issues/134), files plugins must be deleted from Scribite repo. I [noted](https://github.com/zikula-modules/Files/issues/19) this for future dev.

I wait your answers to close this ticket.

**Comment by robbrandt** [comment]
Thanks, I wasn't aware.

I've been using a combination of Content/Scribite/Files forever, and finally was motivated to upgrade to Content 4.10, which meant also Scribite 5.x, which meant the latest Files.  I just did what I had done in previous versions, copying the TinyMCE plugin from the Files module into Scribite.
